In [56]:
import tensorflow as tf


In [42]:
def euclidean(a, b, sqrt=False):
    aTa = tf.linalg.diag_part(tf.matmul(a, tf.transpose(a)))
    bTb = tf.linalg.diag_part(tf.matmul(b, tf.transpose(b)))
    aTb = tf.matmul(a, tf.transpose(b))
    ta = tf.reshape(aTa, [-1, 1])
    tb = tf.reshape(bTb, [1, -1])
    print(ta)
    print(aTb.shape)
    D = ta - 2.0 * aTb + tb
    if sqrt:
        D = tf.sqrt(D)
    return D

In [68]:
A = tf.range(6)

A = tf.reshape(A, [3,2])

print("A:\n", A)
B = tf.convert_to_tensor([[8, 9]])  # 1 个样本的 B
print("B:\n", B)



aTa = tf.linalg.diag_part(tf.matmul(A, tf.transpose(A)))
bTb = tf.linalg.diag_part(tf.matmul(B, tf.transpose(B)))
aTb = tf.matmul(A, tf.transpose(B))
ta = tf.reshape(aTa, [-1, 1])
tb = tf.reshape(bTb, [1, -1])
D = ta - 2 * aTb + tb

A:
 tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)
B:
 tf.Tensor([[8 9]], shape=(1, 2), dtype=int32)


In [69]:
D

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[128],
       [ 72],
       [ 32]])>

In [40]:
def EuclideanDistances(A, B):
    BT = tf.transpose(B) 
    # vecProd = A * BT
    vecProd = tf.matmul(A,BT)
    # print(vecProd)
    SqA =  A**2
    # print(SqA)
    print()
    sumSqA = tf.sum(SqA, axis=1)
    sumSqAEx = np.tile(sumSqA.transpose(), (1, vecProd.shape[1]))
    # print(sumSqAEx)
 
    SqB = B**2
    sumSqB = np.sum(SqB, axis=1)
    sumSqBEx = np.tile(sumSqB, (vecProd.shape[0], 1))    
    SqED = sumSqBEx + sumSqAEx - 2*vecProd
    SqED[SqED<0]=0.0   
    ED = np.sqrt(SqED)
    return ED

In [41]:
A = tf.range(6)

A = tf.reshape(A, [3,2])

print("A:\n", A)
B = tf.convert_to_tensor([[8, 9]])  # 1 个样本的 B
print("B:\n", B)

D = EuclideanDistances(A, B)
print("距离:\n", D)


A:
 tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)
B:
 tf.Tensor([[8 9]], shape=(1, 2), dtype=int32)



AttributeError: module 'tensorflow' has no attribute 'sum'

In [1]:
import torch

def euclidean(a, b, sqrt=False):
    aTa = torch.diag(torch.matmul(a, a.t()))
    bTb = torch.diag(torch.matmul(b, b.t()))
    aTb = torch.matmul(a, b.t())
    D = aTa.view(-1, 1) - 2.0 * aTb + bTb.view(1, -1)
    if sqrt:
        D = torch.sqrt(D)
    return D




In [3]:
A = torch.arange(6).reshape(3, 2)  # 3 个样本的 A
print("A:\n", A)
B = torch.tensor([[8, 9]])  # 1 个样本的 B
print("B:\n", B)

aTa = torch.diag(torch.matmul(A, A.t()))
bTb = torch.diag(torch.matmul(B, B.t()))
aTb = torch.matmul(A, B.t())
D = aTa.view(-1, 1) - 2.0 * aTb + bTb.view(1, -1)


A:
 tensor([[0, 1],
        [2, 3],
        [4, 5]])
B:
 tensor([[8, 9]])


In [4]:
aTa

tensor([ 1, 13, 41])